[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  # Deshabilitar el escáner de secretos para claves de Firebase (que son públicas por diseño)
  SECRETS_SCAN_ENABLED = "false"

# Alternativamente, puedes omitir solo las claves específicas de Firebase:
# [build.environment]
#   SECRETS_SCAN_OMIT_KEYS = "VITE_FIREBASE_API_KEY,VITE_FIREBASE_APP_ID,VITE_FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_MESSAGING_SENDER_ID,VITE_FIREBASE_PROJECT_ID,VITE_FIREBASE_STORAGE_BUCKET"
